# Generated by Django 5.0.14 on 2026-07-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_attempt_hint_used_user_completed_tests_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, help_text='Variantlar (faqat multiple_choice uchun)', null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='audio_url',
            field=models.URLField(blank=True, help_text='Listening testlari uchun audio fayl havolasi', null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='passage',
            field=models.TextField(blank=True, help_text='Reading testlari uchun matn (HTML)', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.JSONField(help_text='To\'g\'ri javoblar ro\'yxati (masalan: ["apple", "apples"])'),
        ),
    ]
